trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/*.sln'

steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: restore
      restoreSolution: '$(solution)'
      feedsToUse: 'select'

  - task: VSBuild@1
    displayName: 'Build solution'
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - script: echo Build done.
    displayName: 'Notify build done'
